language: go

go:
  - 1.8.x
  - tip

env:
  global:
    - secure: "F3tvn+oUqgAJp1oaBbemwJJ85FvVqrTDQ/bLdGtjnNihhfOggmyo4ccsCBwvbUx1CIk/uEor60+FXETgJ0plyzocUi2vFFr4Se3ohNIR7O/VCikbQ3a3J/ZWYjJsBjfX3Jth10mtxQssBWl/iNofep0zrRynpE+EbiFg7N1+r5B2TgIhz5Z1ShMg9pBARfaQqa2SGQxXj0GJz5odDPap4Kaj/6zZINXKlIzxYbvxGe0Ki5UrHiPjQQs4XyTDf15zQHdiExHXa5eptExGRZ3HL2KGOoNHRaMt0txvyWCdkP2zNUjbczDs/bsb8xVC/RqF9cLUS4DkpWshUiz2y9PLKtYeTgYyGyE6jbf9X5zhUyrgrFuLvnzJV6Mjg/EjCllvSW246AJGIC7C37gbENp+Et+2qX6Rg7AuetE8lqCy9VuCHxK75tFst4YLDnmIPwdUqZn7rwYD2+FRBFBT+gGoxhHNYBfgtHt5Lj9B5VYUZ4MXpT/ywTjJL6wuq9ce5jOTxKgNDYcI8OP32Ppdk/rvwx8gFMFvLW6KqciMLh9FyimidUzSZ3/43EALtaNovQlR//2qbSj7Cj2E0Q7wwdvJZqEZ85eDDtr2tUxSp5qO+are8MbTu+4Xm9Nsdpj7FpvWIgUYSFz4Zc6SuPo+T83bX15ikXofUMbHGtYWngnqNuQ="
before_install:
  - |

       $(npm bin)/set-up-ssh --key "$encrypted_614bca37b351_key" \
                             --iv "$encrypted_614bca37b351_iv" \
                             --path-encrypted-key ".travis/github_ci_key.enc"

install:
  - go get github.com/Masterminds/glide
  - glide --no-color up
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - gometalinter --vendor --disable-all --enable=vet --enable=goimports --enable=vetshadow --enable=golint --enable=ineffassign --enable=goconst --tests ./...
  - ./run-tests.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
